require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context
    - shared_examples
    - it

Naming/FileName:
  Exclude:
    - lib/ruby-terraform.rb

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 40

Gemspec/RequireMFA:
  Enabled: false
