# frozen_string_literal: true

require_relative 'commands/apply'
require_relative 'commands/clean'
require_relative 'commands/destroy'
require_relative 'commands/force_unlock'
require_relative 'commands/format'
require_relative 'commands/get'
require_relative 'commands/graph'
require_relative 'commands/import'
require_relative 'commands/init'
require_relative 'commands/login'
require_relative 'commands/logout'
require_relative 'commands/output'
require_relative 'commands/plan'
require_relative 'commands/providers'
require_relative 'commands/providers_lock'
require_relative 'commands/providers_mirror'
require_relative 'commands/providers_schema'
require_relative 'commands/refresh'
require_relative 'commands/show'
require_relative 'commands/state_list'
require_relative 'commands/state_move'
require_relative 'commands/state_pull'
require_relative 'commands/state_push'
require_relative 'commands/state_replace_provider'
require_relative 'commands/state_remove'
require_relative 'commands/state_show'
require_relative 'commands/taint'
require_relative 'commands/untaint'
require_relative 'commands/validate'
require_relative 'commands/workspace_delete'
require_relative 'commands/workspace_list'
require_relative 'commands/workspace_new'
require_relative 'commands/workspace_select'
require_relative 'commands/workspace_show'

module RubyTerraform
  module Commands
  end
end
